### ISSUE TITLE
Reporting results error

### ISSUE THREAD

**Issue by jiapangpang** [currents-dev/cypress-cloud#100]
my config 
```
  const { totalFailed } = await cyCloud.run({
    record: true,
    headless: true,
    parallel: true,
    config:{
      video: true,
      videoUploadOnPasses:true
    },
    key: recordKey,
    spec: pathToSpec,
    project: pathToProject,
    configFile: runConfigFile,
    ciBuildId: 'cikeys123',
  });
```
## Describe the bug
In sorry-cypress, in function [getVideoUploadUrl](https://github.com/sorry-cypress/sorry-cypress/blob/6cce0d3b257d32a0e62970feb0cc115226ad656a/packages/director/src/screenshots/minio.driver.ts#L25) `reuslt` need to check  `cypressConfig` to getUrl

but in cyprss-cloud  `instanceResults` in runtime dont have  `cypressConfig`
https://github.com/currents-dev/cypress-cloud/blob/249335b88116265401521dcfee2856784f6f0dbe/packages/cypress-cloud/lib/results/uploadResults.ts#L92

## Expected behavior
upload video

**Comment by agoldis** [comment]
@jiapangpang thanks for submitting the issue, would you mind please following the template and provide all the details

**Comment by jiapangpang** [comment]
oh,it is my fault, sorry
