### ISSUE TITLE
Unable to resolve spec file from custom project location

### ISSUE THREAD

**Issue by zinkjm** [currents-dev/cypress-cloud#114]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 11.7.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 139.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.146
    Firefox: 110.0.1
    Safari: 16.2
  npmPackages:
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    @octokit/rest: ^18.12.0 => 18.12.0 (19.0.3)
    @typescript-eslint/eslint-plugin: ^5.55.0 => 5.55.0 
    @typescript-eslint/parser: ^5.55.0 => 5.55.0 
    audit-ci: ^6.6.1 => 6.6.1 
    cross-env: ^7.0.3 => 7.0.3 
    cypress: ^12.9.0 => 12.9.0 
    cypress-cloud: ^1.6.0 => 1.6.0 
    eslint: ^8.36.0 => 8.36.0 
    eslint-plugin-import: ^2.27.5 => 2.27.5 
    eslint-plugin-import-quotes: ^0.0.1 => 0.0.1 
    husky: ^8.0.3 => 8.0.3 
    lerna: ^6.5.1 => 6.5.1 
    npm-check-updates: ^16.7.12 => 16.7.12 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.11.0

```

</details>

### Describe the bug

When I run the cypress-cloud command with the custom --project flag, it finds the spec files from the given pattern, but when it goes to run each file, it says there are no spec files found.

### Expected behavior

I expect the spec files to run from the project root that I entered with --project flag

### Command and Setup

npx cypress-cloud --project packages/cypress --specPattern "./packages/cypress/integration/**/*.test.js --record --ci-build-id BUILD_ID

### Full log and debug output

<details>

// Put your logs below this line
[debug.txt](https://github.com/currents-dev/cypress-cloud/files/11140926/debug.txt)

</details>

**Comment by agoldis** [comment]
A fix is on the way
