### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by MadSandwich** [currents-dev/cypress-cloud#125]
### Description

Support ESM to parse path correctly.
(I hope I describe it at least understandable =) )

### Example usage

Set `type:module` in package.json file and use default config to run tests:
![image](https://user-images.githubusercontent.com/57759145/233666882-4e0c0aea-d075-4b7c-909b-1dd68ccb6004.png)

**Comment by samixchoumi** [comment]
A must have, using `@badeball/cypress-cucumber-preprocessor`, if I remove `type:module`, it will crash my run command.

`2023-06-13T13:14:38.196Z cypress:lifecycle:child:RunPlugins:50466 plugins file errored: TypeError: Cannot read properties of undefined (reading 'addCucumberPreprocessorPlugin')`

**Comment by MadSandwich** [comment]
@agoldis unfortunately for me, it's still reproducing.
![image](https://github.com/currents-dev/cypress-cloud/assets/57759145/950aa93f-e016-47cd-a815-36cfb8bb6284)
in package.json ->         "cypress-cloud": "^1.8.0-beta.5",

**Comment by MadSandwich** [comment]
@agoldis unfortunately I can't share such logs, they have information that I couldn't share. But I've created a minimal reproducible example.
https://github.com/MadSandwich/Cypress

And here the error that I've receive with such setup, I have same configurations on my real repo and same errors, so that probably could help to find where an actual problem. (Maybe I missing something. All settings in the config was set to likely non-existing, just to show an error)
![image](https://github.com/currents-dev/cypress-cloud/assets/57759145/fcf34aec-f90c-4e90-a96c-7cffc7db2154)

**Comment by samixchoumi** [comment]
Do the export for each variable instead of export default. 
And be sure to use the beta version on the package.json as mentioned previously. Then Retry and send the logs (you can change confidential data)

**Comment by agoldis** [comment]
@MadSandwich please remove the sensitive information, it'd greatly speed up the troubleshooting

**Comment by MadSandwich** [comment]
@samixchoumi
1. It was done in my previous example.
2. Yes, I've double checked, that I use beta version.

Here is the simple video of trying 2 ways of configuration.
https://github.com/currents-dev/cypress-cloud/assets/57759145/99d9a11e-ae90-4d01-bdbe-5876fc96674c

@agoldis, I've made an repo where u can check everything you need, because, I not sure, that I cover all needed for you details. Hope it will help u more.

**Comment by agoldis** [comment]
@MadSandwich can you please enable the debug mode and share the logs from the repo you created. Thank you

**Comment by MadSandwich** [comment]
@agoldis 
```
> cy:ci
> cypress-cloud --parallel --record --ci-build-id 1

  currents:capture capturing stdout +0ms
  cypress:cli exporting Cypress module interface +0ms
  currents:cli parsed CLI flags { component: false, e2e: true, parallel: true, record: true, headed: false, ciBuildId: '1' } +0ms
  currents:cli parsed run params: { parallel: true, record: true, headed: false, ciBuildId: '1', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: undefined } +2ms
  currents:run run params { parallel: true, record: true, headed: false, ciBuildId: '1', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: undefined } +0ms
  currents:run params after preprocess { parallel: true, record: true, headed: false, ciBuildId: '1', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: undefined, spec: undefined } +1ms
  currents:config loading currents config file from 'C:\Users\Artem\projects\Cypress\currents.config.js' +0ms
  currents:config failed loading config file from: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' +2ms
  currents:config loading currents config file from 'C:\Users\Artem\projects\Cypress\currents.config.cjs' +1ms
  currents:config failed loading config file from: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' +1ms
  currents:config loading currents config file from 'C:\Users\Artem\projects\Cypress\currents.config.mjs' +1ms
  currents:config failed loading config file from: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' +0ms
 WARNING  Failed to load config file, falling back to the default config. Attempted locations: [
  'C:\\Users\\Artem\\projects\\Cypress\\currents.config.js',
  'C:\\Users\\Artem\\projects\\Cypress\\currents.config.cjs',
  'C:\\Users\\Artem\\projects\\Cypress\\currents.config.mjs'
]
  currents:validateParams resolving currents params: { parallel: true, record: true, headed: false, ciBuildId: '1', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: undefined, spec: undefined } +0ms
  currents:validateParams resolving currents config file: { e2e: { batchSize: 3 }, component: { batchSize: 5 }, cloudServiceUrl: 'https://cy.currents.dev' } +1ms
  currents:validateParams validating currents params: { parallel: true, record: true, headed: false, ciBuildId: '1', config: undefined, env: undefined, reporterOptions: undefined, testingType: 'e2e', recordKey: undefined, spec: undefined, cloudServiceUrl: 'https://cy.currents.dev', projectId: undefined, batchSize: 3 } +0ms
 ERROR  Cannot resolve projectId. Please use one of the following:
- provide it as a "projectId" property for "run" API method
- set CURRENTS_PROJECT_ID environment variable
- set "projectId" in "currents.config.{c}js" file
```

**Comment by agoldis** [comment]
@MadSandwich Please try using cypress-cloud@1.8.0-beta.6, should be good for ESM on Windows

**Comment by MadSandwich** [comment]
> @MadSandwich Please try using cypress-cloud@1.8.0-beta.6, should be good for ESM on Windows

Everything looks good. Thanks! The issue can be closed after merging this fix.
