### ISSUE TITLE
How to combine cypress-cloud and cypress-ntlm

### ISSUE THREAD

**Issue by RuslanAisin** [currents-dev/cypress-cloud#131]
### Description

Hello!
Is it possible to combine cypress-cloud and cypress-ntlm? 
If I run tests cypress-cloud I have problem with ntlm auth. On the other hand cypress-ntlm cant change env

### Example usage

When needs to run test with ntlm auth

**Comment by agoldis** [comment]
@RuslanAisin 
You need to start ntlm-proxy in a standalone mode as described here: https://github.com/bjowes/cypress-ntlm-auth#ntlm-proxy

Starting the proxy and setting the appropriate environment variables will enable ntlm functionality in cypress test.

**Comment by RuslanAisin** [comment]
This issue help for me.
https://github.com/bjowes/cypress-ntlm-auth/issues/235
