### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by marcusds** [currents-dev/cypress-cloud#135]
There is no license file in the repo and the license link into the readme goes to a 404.

Automated tools at work prevent me from using any project without a license if one could be added that would be amazing, thanks.

**Comment by marcusds** [comment]
Oh I see it's under the packages folder. The readme link is still missing. I wonder if my automated tool at work isn't finding it since isn't in the root?

**Comment by agoldis** [comment]
Moved to root
