### ISSUE TITLE
Question: Why not seeing the current test on 'npx cypress-cloud run' command

### ISSUE THREAD

**Issue by Ido112** [currents-dev/cypress-cloud#154]
Hi,
When i used the dashboard of cypress.io i saw the current test that pass successfully / failed on the CLI
Now when i start to use `npx cypress-cloud run`  i cannot see it anymore
Just Running: and the same of the spec file.

Any suggestion?

![image](https://github.com/currents-dev/cypress-cloud/assets/32884355/297998ab-cef5-46d0-8604-94d72b788444)

**Comment by agoldis** [comment]
@Ido112 sorry, what do you mean?

**Comment by Ido112** [comment]
When i run Currents dev on the cli 

![image](https://github.com/currents-dev/cypress-cloud/assets/32884355/40438334-9b34-43a1-bc86-c5aea5585fea)


When i run cyperss

![image](https://github.com/currents-dev/cypress-cloud/assets/32884355/dc1f448d-ef96-4d68-97b6-92014c58f210)

**Comment by Ido112** [comment]
When i run currents dev on the cli 

![image](https://github.com/currents-dev/cypress-cloud/assets/32884355/750511aa-89a2-43c1-8012-21cf103e8ecf)


When i runs cypress on the cli

**Comment by Ido112** [comment]
I run currents with the function run

![image](https://github.com/currents-dev/cypress-cloud/assets/32884355/01307a9b-e3b5-4ee1-8db3-02ea2f6bfa0b)

**Comment by agoldis** [comment]
@Ido112 Gotcha, Because of `reporter: "junit"`
