### ISSUE TITLE
Executing requirements before execution of all spec files

### ISSUE THREAD

**Issue by SebeFromGermany** [currents-dev/cypress-cloud#159]
### Description

We need the possibility to execute js/typescript code before cypress-cloud connects to the cloud orchestration service. 
![image](https://github.com/currents-dev/cypress-cloud/assets/94075556/ae6e8f03-1b38-4202-a969-79fb9a92e368)

With cy2 we prepared our client for testing in the setupNodeEvents() in the cypress.config file. This is not possible with cypress-cloud because it's executed for every spec file and not just at the beginning of the run.

### Example usage

```
e2e: {
    ...e2e,
    setupNodeEvents(on, config) {
//executing client preparation steps
      return cloudPlugin(on, config);
    },
  },
```

**Comment by agoldis** [comment]
See an example here: https://github.com/currents-dev/cypress-cloud/blob/main/examples/webapp/scripts/currents-script.ts#L9
