### ISSUE TITLE
Mochawesome.json is always deleted for each spec file ran

### ISSUE THREAD

**Issue by firmanserdana** [currents-dev/cypress-cloud#161]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Previously using cy2, the mochawesome.json in report folder wont be deleted after each spec file iteration.

But now cypress-cloud will delete it and looks like it compiles into dashboard by default.

### Expected behavior

.json report file shouldn't be deleted

### Command and Setup

npx cypress-cloud ***

selfhosted in aws

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>
N/A for this issue

**Comment by agoldis** [comment]
cypress-cloud doesn't delete anything during its execution. Most likely restarting cypress from scratch triggers the delete. Please double check the reported configuration and preserve the reports between restart. Also please follow the template next time

**Comment by firmanserdana** [comment]
Yes, thank you @agoldis I have set the workaround and made it work 👍
