### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by redbugz** [currents-dev/cypress-cloud#193]
### Description

https://www.cypress.io/blog/2023/11/07/update-defense-intellectual-property

I'm guessing this is a sensitive topic, but would it be possible to rename the project and resolve this dispute with Cypress so we can continue to use our self-hosted sorry-cypress dashboard?
I am very grateful for all the hard work put into maintaining this and sorry-cypress, and I recognize the frustration over this dispute. But I would prefer that the open source portions stay compatible with Cypress and if changing the name would allow it to move forward that seems like a relatively reasonable compromise.
I would be willing to help with the migration and renaming if it would be accepted.

### Example usage

A generic name that doesn't conflict like `dash-runner`, if you still want to promote your company than perhaps `currents-cloud` or `currents-runner`, or something unrelated like an animal name or abstract term like `muse-runner` or whatever.

**Comment by firmanserdana** [comment]
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries

even the older versions are being blocked now, I don't think it will work by just changing the name

**Comment by issa-evooq** [comment]
is there any known workaround for this? other than completely disabling currents that is

**Comment by samixchoumi** [comment]
@firmanserdana You should pin this comment as a working solution, it works like a charm.
