### ISSUE TITLE
Cypress binaries

### ISSUE THREAD

**Issue by tomasz-hofy** [currents-dev/cypress-cloud#194]
It seem Cypress has build in the blocking mechanism into the binary. Does anyone have somewhere access mechanism to old binaries of 12.17.4 ? I am planning to precache them and prevent cypress from downloading the "broken" on before we migrate to Playwright.

**Comment by agoldis** [comment]
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries

**Comment by MaksimYaginov** [comment]
Please upload another version 12.14.0 because the cypress allure plugin works with it

**Comment by agoldis** [comment]
@MaksimYaginov released for `linux-x64`
