### ISSUE TITLE
Errors while running parallel tests with cypress-cloud

### ISSUE THREAD

**Issue by knidhi** [currents-dev/cypress-cloud#199]
### Please confirm

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I will include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
    Memory: 16.18 GB / 31.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/software/toolchain/x86_64-linux/7.1/bin/node
    npm: 8.15.0 - ~/software/toolchain/x86_64-linux/7.1/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
  npmGlobalPackages:
    corepack: 0.12.1
    npm: 8.15.0


```

</details>

### Describe the bug

After months of running smoothly on our Jenkins we have recently started seeing the following error:

11:37:25 my-repo-e2e:  ERROR  Unable to resolve cypress configuration
11:37:25 my-repo-e2e: - make sure that 'cypress-cloud/plugin' is installed

Cypress version: 12.12.0
Cypress-cloud version: 1.7.0
agoldis/sorry-cypress-director: 2.5.3

Could this be related to blocks imposed by cypress.io? There haven't been any version upgrades in past couple of months.

### Expected behavior

Tests should run as expected since the plugin clearly exists in node/modules directory

### Setup and Command

npx cypress-cloud --quiet --project $(npm prefix)/apps/iris-ui-angular-e2e --spec **/*.ci.spec.* --parallel --record --key irisUiKey --ci-build-id 111 --config baseUrl=https://localhost:4200,video=false

Cypress config:
import { defineConfig } from "cypress";
import { cloudPlugin } from "cypress-cloud/plugin";
export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      const result = cloudPlugin(on, config);
      return result;
    },
  },
});

### Full log and debug output

<details>

```
// Put your logs below this line
11:37:19 my-repo-e2e: Using config file: 'file:///mnt/disk1/workspace/Gerrit-Verify-my-ui/my-ui/iris/apps/my-repo-e2e/currents.config.js'
11:37:19 my-repo-e2e: Copyright (C) 2023 Currents Software Inc https://currents.dev
11:37:19 my-repo-e2e: This is free software, and you are welcome to redistribute it under certain
11:37:19 my-repo-e2e: conditions. This program comes with no warranty. Parts of this program are MIT
11:37:19 my-repo-e2e: licensed. Refer to the license for details
11:37:19 my-repo-e2e: https://github.com/currents-dev/cypress-cloud/blob/main/LICENSE.md
11:37:19 my-repo-e2e: {"level":30,"time":1700806039616,"msg":"🔧 Director execution driver: in-memory"}
11:37:19 my-repo-e2e: {"level":30,"time":1700806039617,"msg":"🎧 Initializing listeners for hooks..."}
11:37:20 my-repo-e2e: {"level":30,"time":1700806039620,"msg":"🚀 Director service is ready at http://0.0.0.0:1234/..."}
11:37:21 my-repo-e2e: [Cypress-Parallel] Pid: Thread 1: 19433
11:37:22 argus-e2e:     Compression progress:  53%
11:37:24 my-repo-e2e: Using config file: 'file:///mnt/disk1/workspace/Gerrit-Verify-my-ui/my-ui/iris/apps/my-repo-e2e/currents.config.js'
11:37:24 my-repo-e2e: Copyright (C) 2023 Currents Software Inc https://currents.dev
11:37:24 my-repo-e2e: This is free software, and you are welcome to redistribute it under certain
11:37:24 my-repo-e2e: conditions. This program comes with no warranty. Parts of this program are MIT
11:37:24 my-repo-e2e: licensed. Refer to the license for details
11:37:24 my-repo-e2e: https://github.com/currents-dev/cypress-cloud/blob/main/LICENSE.md
11:37:25 my-repo-e2e: Cypress stdout:
11:37:25 my-repo-e2e:  
11:37:25 my-repo-e2e: Cypress stderr:
11:37:25 my-repo-e2e:  
11:37:25 my-repo-e2e:  ERROR  Unable to resolve cypress configuration
11:37:25 my-repo-e2e: - make sure that 'cypress-cloud/plugin' is installed
11:37:25 my-repo-e2e: - report the issue together with cypress stdout and stderr
11:37:26 my-repo-e2e: [Cypress-Parallel] Pid: Thread 2: 19762
11:37:29 my-repo-e2e: Using config file: 'file:///mnt/disk1/workspace/Gerrit-Verify-my-ui/my-ui/iris/apps/my-repo-e2e/currents.config.js'
11:37:29 my-repo-e2e: Copyright (C) 2023 Currents Software Inc https://currents.dev
11:37:29 my-repo-e2e: This is free software, and you are welcome to redistribute it under certain
11:37:29 my-repo-e2e: conditions. This program comes with no warranty. Parts of this program are MIT
11:37:29 my-repo-e2e: licensed. Refer to the license for details
11:37:29 my-repo-e2e: https://github.com/currents-dev/cypress-cloud/blob/main/LICENSE.md

```

</details>

**Comment by knidhi** [comment]
Update:
I m able to execute tests on windows 10. Issue seems to be specific to Ubuntu environment.

**Comment by dsgkirkby** [comment]
We've encountered this as well trying to upgrade to cypress 12. Our tests still pass on cypress 11 though. It fails in CI on a linux machine but passes locally on my mac.

#### Versions
`cypress`: 12.17.4
`cypress-cloud`: 1.9.6
`agoldis/sorry-cypress-director`: 2.5.10

#### Logs
```
$ /home/jenkins/agent/workspace/.../node_modules/.bin/cypress-cloud run --browser /usr/bin/google-chrome-stable --parallel --group concurrent --spec 'cypress/e2e/concurrent/**/*' --record --ci-build-id {build-id}
Using config file: 'file:///home/jenkins/agent/workspace/.../currents.config.js'

Copyright (C) 2023 Currents Software Inc https://currents.dev/
This is free software, and you are welcome to redistribute it under certain
conditions. This program comes with no warranty. Parts of this program are MIT
licensed. Refer to the license for details
https://github.com/currents-dev/cypress-cloud/blob/main/LICENSE.md

Cypress stdout:
 
Cypress stderr:
 
 ERROR  Unable to resolve cypress configuration
- make sure that 'cypress-cloud/plugin' is installed
- report the issue together with cypress stdout and stderr
```

**Comment by dsgkirkby** [comment]
I enabled debug logging (added the environment variable `DEBUG=*`) and found this in the logs: `We've detected that you're using a 3rd party library that is not supported by Cypress: cypress-cloud` - so it seems like cypress is blocking 3rd party plugins even on v12, not just v13.

**Comment by agoldis** [comment]
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries
