### ISSUE TITLE
Record key can't be found

### ISSUE THREAD

**Issue by Abcmsaj** [currents-dev/cypress-cloud#67]
### Before opening, please confirm:

- [X] I have searched for duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

Our problem is a weird one around the record key... I didn't think we needed to pass the --key in the start up command when we were using currents/cli. Our record key is stored as a variable inside the pipeline runs in Azure. Now getting this error:

```
It currently has the projectId: XXXXXX

You also provided your Record Key, but you did not pass the --record flag.

This run will not be recorded.

If you meant to have this run recorded please additionally pass this flag:

  $ cypress run --record

If you don't want to record these runs, you can silence this warning:

  $ cypress run --record false

https://on.cypress.io/recording-project-runs

```

Now I have updated our startup command to this:

npx cypress-cloud run --browser chrome --config-file cypress/config/${{ parameters.environmentName }}.config.js --record --key $(CYPRESS_RECORD_KEY) --parallel --ci-build-id $(GUID) --spec "cypress/e2e/$(UI_AREA)/**/*.spec.ts" --tag $(CY_TAG) --env tags=$(UI_AREA)

where I am passing the key after --record but I am still seeing the error above

</details>

### Describe the bug

Even though we are passing a record key from an configuration on our pipeline, the CLI claims we are not. We tried it with and without the record key inside currents.config.js and both gave us the error above

### Expected behavior

I would expect the startup command I posted to work without telling us that the key is missing. Oddly, it still does seem to record to Currents anyway!

### Command and Setup

npx cypress-cloud run --browser chrome --config-file cypress/config/${{ parameters.environmentName }}.config.js --record --key $(CYPRESS_RECORD_KEY) --parallel --ci-build-id $(GUID) --spec "cypress/e2e/$(UI_AREA)/**/*.spec.ts" --tag $(CY_TAG) --env tags=$(UI_AREA)

### Full log and debug output

<details>

```
// Put your logs below this line
It currently has the projectId: XXXXXX

You also provided your Record Key, but you did not pass the --record flag.

This run will not be recorded.

If you meant to have this run recorded please additionally pass this flag:

  $ cypress run --record

If you don't want to record these runs, you can silence this warning:

  $ cypress run --record false

https://on.cypress.io/recording-project-runs

```

</details>

**Comment by agoldis** [comment]
Please use `CURRENTS_RECORD_KEY` env variable, as appears in documentation
