### ISSUE TITLE
`(intermediate value).default is not a function` is being return when running cypress-cloud commands

### ISSUE THREAD

**Issue by bilarallen** [currents-dev/cypress-cloud#71]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.10 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800U with Radeon Graphics
    Memory: 2.92 GB / 6.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
  npmPackages:
    @currents/cli: ^4.0.3 => 4.0.3 
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    @faker-js/faker: ^7.6.0 => 7.6.0 
    cypress: ^12.7.0 => 12.7.0 
    cypress-cloud: ^1.4.2 => 1.4.2 
    cypress-recurse: ^1.27.0 => 1.27.0 
    fs: ^0.0.1-security => 0.0.1-security 
    moment: ^2.29.4 => 2.29.4 
    numeral: ^2.0.6 => 2.0.6 
    q: ^1.5.1 => 1.5.1 
    shelljs: ^0.8.5 => 0.8.5 
    swagger-client: ^3.18.5 => 3.18.5 
    xvfb: ^0.4.0 => 0.4.0 
  npmGlobalPackages:
    npm: 6.14.13


```

</details>

### Describe the bug

When running the command `npx cypress-cloud --parallel --record --key <your_key> --ci-build-id hello-cypress-cloud` the CLI always return `(intermediate value).default is not a function` and doesn't run the test

### Expected behavior

Should be able to run the test using cypress-cloud

### Command and Setup

*projectRoot/currents.config.js file
```
module.exports = {
  projectId: "Sun9p6",
  recordKey: "*******",
  cloudServiceUrl: "https://cy.currents.dev",
};
```

=========================================
*projectRoot/cypress.config.js file

```
const { defineConfig } = require("cypress");
const { cloudPlugin } = require("cypress-cloud/plugin");

module.exports = defineConfig({
  e2e: {

    setupNodeEvents(on, config) {
      return cloudPlugin(on, config);
    },
  },
});
```
============================================

### Full log and debug output

![image](https://user-images.githubusercontent.com/65072341/224258611-12086990-6262-4e20-8335-bf84d2f4632b.png)

**Comment by agoldis** [comment]
ok, it is related to npm incorrectly resolving one the peerDependency of a dependency 🤦🏻‍♂️

**Comment by agoldis** [comment]
@bilarallen please try using 1.4.3+
