### ISSUE TITLE
Module API (1.4.4) not working with Javascript

### ISSUE THREAD

**Issue by mirobo** [currents-dev/cypress-cloud#80]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

`cypress: ^12.7.0 => 12.7.0`
`cypress-cloud: ^1.4.4 => 1.4.4`

`npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages`

<details>

```

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.35 GB / 31.74 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @cypress/angular:  0.0.0-development
    @cypress/mount-utils:  0.0.0-development
    @cypress/react:  0.0.0-development
    @cypress/react18:  0.0.0-development
    @cypress/svelte:  0.0.0-development
    @cypress/vue:  0.0.0-development
    @cypress/vue2:  0.0.0-development
    cypress: ^12.7.0 => 12.7.0
    cypress-cloud: ^1.4.4 => 1.4.4
  npmGlobalPackages:
    corepack: 0.15.2
    npm: 8.19.3
    rimraf: 4.1.2
```
</details>

### Describe the bug

I'm not able to use the cypress-cloud module API within a JS file.

Starting cypress-cloud via "npx cypress-cloud" works fine. But it is still a blocker since I cannot pass Cypress config options to "npx cypress-cloud".

I dynamically configure some Cypress env variables in a JavaScript file and because of it I need (it is much more convenient) to start cypress-cloud via the Module API

### Expected behavior

Module API works everywhere :)

### Command and Setup

Simple demo project: https://github.com/mirobo/cypress-cloud-module-api

Run commands:
- npm i
- node run-tests-ci.js

### Full log and debug output

```
C:\views\_\cypress-cloud-module-api>node run-tests-ci.js
node:internal/modules/cjs/loader:544
      throw e;
      ^

Error: Cannot find module 'C:\views\_\cypress-cloud-module-api\node_modules\cypress-cloud\'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1060:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1053:15)
    at resolveExports (node:internal/modules/cjs/loader:538:14)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\views\_\cypress-cloud-module-api\run-tests-ci.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1218:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\views\\_\\cypress-cloud-module-api\\node_modules\\cypress-cloud\\package.json'
}

Node.js v18.13.0
```

**Comment by agoldis** [comment]
Thanks for reporting @mirobo, will fix ASAP

**Comment by agoldis** [comment]
I've published 1.4.5-beta.0 on npm - please confirm it's working for you

**Comment by mirobo** [comment]
It seems like it's not published?

https://www.npmjs.com/package/cypress-cloud?activeTab=versions

![image](https://user-images.githubusercontent.com/78788210/225578829-b4ceae53-82f8-4551-9fa1-51a252fdb8af.png)

Stupid question.. did you run these commands from your own documentation? 😉😁
```
cd packages/cypress-cloud
npm run release -- --preRelease=beta && npm run release:npm -- -t beta
```

**Comment by agoldis** [comment]
weird
<img width="696" alt="currents-2023-03-16-03 07 26@2x" src="https://user-images.githubusercontent.com/1637928/225584363-cfe2f0a7-8e39-4be3-a659-5d432ed1974e.png">

**Comment by mirobo** [comment]
Now I see it.. I'll get back to you later!

**Comment by mirobo** [comment]
Calling the "run" function now works, but the plugin itself can no longer communicate with sorry-cypress (error 400).

I tested it twice, with two instance of sorry-cypress (one with version 2.5.3 and one with 2.1.3). They both responded with error "400". I guess it's purely a client side error but it's suboptimal that the Module API version just returns an undefined object rather than some kind of error message details like with the command "npx cypress-cloud".

Error from "./run-tests-ci.**sh**" command (this worked in 1.4.4):
```
 ERROR  Error: Request failed with status code 400
    at C:\views\_\cypress-cloud-module-api\node_modules\lib\httpClient\httpClient.ts:92:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createRun (C:\views\_\cypress-cloud-module-api\node_modules\lib\api\api.ts:17:20)
    at run (C:\views\_\cypress-cloud-module-api\node_modules\index.ts:70:15)
```

Error from "node run-tests-ci.js" command:

```
...
const result = await run({
    ciBuildId: getCiBuildId(),
  }).catch((err) => {
    console.error(`error occurred`);
    console.error(JSON.stringify(err, null, 2));
    exitCode = 999;
  });
...
```
produced output:

```
error occurred
{}
Result object from cypress-cloud run command:
undefined
```

Full logs and used scripts are here:

https://github.com/mirobo/cypress-cloud-module-api/blob/main/run-tests-ci.sh
https://github.com/mirobo/cypress-cloud-module-api/blob/main/log-sh.txt

https://github.com/mirobo/cypress-cloud-module-api/blob/main/run-tests-ci.js
https://github.com/mirobo/cypress-cloud-module-api/blob/main/log-js.txt

**Comment by agoldis** [comment]
@lpanger what version of the package are you using? We have released https://www.npmjs.com/package/cypress-cloud/v/1.4.5-beta.1, working on the production release rn.

As for the errors - it requires node 14.7.0+, weird I am not seeing those when testing locally. How do I reproduce it?
