### ISSUE TITLE
Fail to run cypress-cloud with 'connect ECONNREFUSED 127.0.0.1:80'

### ISSUE THREAD

**Issue by psimona** [currents-dev/cypress-cloud#90]
When running 

```
npx cypress-cloud run --parallel --record --key somekey --ci-build-id hello-cypress
```

we obtain a connection error as follows

```
Discovered 7 spec files
Tags: false; Group: false; Parallel: true; Batch Size: 3
Connecting to cloud orchestration service...
 WARNING  Network request failed: 'connect ECONNREFUSED 127.0.0.1:80'. Next attempt is in 15s (1/3).
```

This is the `currents.config.js` file

```
module.exports = {
  projectId: 'some-project', // the projectId
  recordKey: 'some-key', // the record key, can be any values for sorry-cypress users
  // Sorry Cypress users - set the director service URL
  cloudServiceUrl: 'http:://localhost:1234',
};
```

Director is running via docker with command

```
docker run -p 1234:1234 agoldis/sorry-cypress-director
```

cypress cloud version is 1.4.4

Expected is that cypress runs and multiple agents can be started in parallel.

Thank you in advance for your time

**Comment by agoldis** [comment]
@psimona please use the template when creating issues next time. Also, make sure to check the configuration.
![currents-2023-03-16-13 01 34@2x](https://user-images.githubusercontent.com/1637928/225739509-960af77a-b77e-4714-9789-b73c0e939bb8.png)

**Comment by psimona** [comment]
@agoldis Thanks for spotting the issue, it drove me crazy!
